### ISSUE TITLE
[bug][launcher] PTT Not Working on macOS Catalina T799

### ISSUE THREAD

**Issue by KWB** [swift-project/pilotclient#20]
It seems the swift launcher cannot receive any key inputs (keyboard strokes, mouse keys or flight stick buttons) when setting up PTT. Testing after manual selection did not work either. There can be a bug with the key listening logic on modern macOS.

swift version: 0.9.4.377
macOS version: 10.15.5 Beta (19F83c)

I have tried to enable all relevant permissions.

**Comment by CaptainYukinoshitaHachiman** [comment]
Now on macOS Big Sur, flight stick button inputs can be detected, but others still don't quite work.

**Comment by oktal3700** [comment]
Closing due to lack of information and no recent reports. All issues so far have been solved by going into System Preferences -> Input Monitoring and making sure swiftgui and swiftlauncher have permission to directly access the keyboard and joystick. Anyone still experiencing an issue should create a new ticket with **_more details_** than those that have been provided here.
