### ISSUE TITLE
Getting Timeout Errors

### ISSUE THREAD

**Issue by AirLuSa** [swift-project/pilotclient#203]
Since the new automatic server selection. I need nearly five times until swift is going to connect to vatsim.

**Comment by ltoenning** [comment]
@AirLuSa Do you still encounter these problems? Are you using a WiFi or Ethernet/cable connection to your router?

**Comment by AirLuSa** [comment]
I am using wifi. And also with the latest 13. Release I encounter the problem.

**Comment by ltoenning** [comment]
We have not received such reports from other users AFAIK. Could you try if using a cable connection works better? Does this website (http://fsd.vatsim.net/) loads for you in a reasonable time?

Otherwise this might be something related to your internet connection and/or how VATSIM automatically selects the the server depending on your connection, geographic location and server load.

**Comment by AirLuSa** [comment]
Unfortunately I cannot test it with cable connection as the router is in another room. But this website loads just fine, an IP address is shown in a second.

**Comment by ltoenning** [comment]
Okay... Using WiFi with swift is a known issue. We cannot do anything about this unfortunately.

If you have the chance to test it with Ethernet in the future and the issue persists, feel free to reopen this issue.

**Comment by AirLuSa** [comment]
Hej, thanks for getting to this again. I am using Mac Os Monterey latest version. Going to test your suggestion soon.

**Comment by AirLuSa** [comment]
Testing without the , looks like it solved the problem. Got an immediate connection.

**Comment by ltoenning** [comment]
Great to hear! This fix will be included in the next upcoming swift version.
If the issue still persists, just reopen this issue or add a comment.
