### ISSUE TITLE
Flight level in flight plan

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#210]
https://discord.com/channels/539048679160676382/568904623151382546/1105397833932214313
> when filing flightplans, using for example FL360, it will show my filed alt as 100000. Not sure if thats a bug, but its minor and can easily be avoided by using 36000ft instead.

**Comment by ltoenning** [comment]
This issue is about the filed FL received by the VATSIM servers (and shown for example by Qutescope or controller clients).

I cannot reproduce this. Neither by 
- typing ``FL360`` into the "Crusing altitude" field and sending it to the server

nor by

- downloading the flightplan from Simbrief and sending it to the server.

In both cases, the correct FL is shown by Qutescope.

I'll try to contact a user who experienced this issue for more information.

**Comment by ltoenning** [comment]
Issue seems to be caused by using the "FLxxx" format inside the FSD flightplan packet. This format is processed correctly by the server and most clients. But Vattastic will display this as  ``100000``.

I'm trying to clarify whether there should be a specific format for the altitude in the flightplan, or if this is an issue of Vattastic .

**Comment by ltoenning** [comment]
There is no convention for the altitude field within the flightplan. As most clients (Euroscope, Qutescope, ...) are supporting "FL###", I will not change this for now in swift.

I wrote a message to the Vattastic developers about the issue.
