### ISSUE TITLE
ATC information ("controller ATIS") always pulls VATSIM data [GERMAN]

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [swift-project/pilotclient#280]
Gestern beim FSeV Gruppenflug: nach Hamburg, EDDH: Alle User der Alpha ....142 Version sahen im Text die  EDDH. ATIS von VATSIM und nicht den Text vom FSC EDDH Tower Controller.  Wir haben dann die neuste Beta genommen und dort wurde der FSC ATIS Text gezeigt. Wieder zurück auf die Alpha.....142 wurde wieder der VATSIM EDDH ATIS Text gezeigt. In der Alpha scheint irgendwie eine Bridge zum Vatsim Server zu sein ( wenn die Tower Frequenzen identisch sind) ?

![Hamburg_mit_Vatsim_ATIS](https://github.com/swift-project/pilotclient/assets/66524946/37cf69de-6152-4259-b7dc-4d469c06b79d)

**Comment by ltoenning** [comment]
Likely related to this change:
https://github.com/swift-project/pilotclient/commit/9cdd624ae0019c7fc4a4aa20f475932b8197f3d0#diff-a5c30df061ab3a930eb8fa8cafa47926a751092e3fba9eacf890c5bf27c543a8L177
With this change (and commit) we always start reading the VATSIM datafile for simplicity. 

The ATIS is  initially always populated from the datafile to avoid delays until getting the real ATIS via FSD:
https://github.com/swift-project/pilotclient/blob/18d0b1eefcb9699d962d2a021b3bfbbd21510ff2/src/blackcore/airspacemonitor.cpp#L675-L676

Previously, this worked fine because the WebDataServices just returned an empty list when not connected to VATSIM.

__Proposed solution__: The ``CAirspaceMonitor`` can check the ecosystem of the connected server. Hence a simple check can be included to avoid populating the station ATIS with VATSIM data when connected to non-VATSIM servers.

**Comment by ltoenning** [comment]
Side note: For adding a new aircraft, something similar is already done :smile: 
https://github.com/swift-project/pilotclient/blob/18d0b1eefcb9699d962d2a021b3bfbbd21510ff2/src/blackcore/airspacemonitor.cpp#L1018-L1021
