### ISSUE TITLE
[CI] Generate Doxygen documentation in Github Actions

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#43]
We also need to install the Qt docs, to fix the `@copybrief or @copydoc target not found` warnings, but `install-qt-action` doesn't support this.

- [x] done

**Comment by oktal3700** [comment]
Also related to `install-qt-action` we need to also install the Debug Info to fix the MSVC warning `LNK4099: PDB 'qtmain.pdb' was not found`.

**Comment by oktal3700** [comment]
Now we just need to push the generated docs to the web.

**Comment by ltoenning** [comment]
I guess the files aren't changing much between new commits/versions, right? 
Then static webhosting via an AWS S3 bucket might be an option using AWS CLI with https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html. This will only upload changed files. 

Pricing for the storage shouldn't be the problem but 0.005$ for 1.000 PUT requests. In my local build, we currently have ~21.000 files :(

Otherwise, we can ask @tzobler if we might host it on FSC servers. (Around 1.4 GB disk usage).

**Comment by tzobler** [comment]
I have no problem hosting this at the FSC. What exactly do we need? How can we redirect the URL?  

a3g Thomas

 

Von: Lars Toenning [mailto:notifications@github.com] 
Gesendet: Freitag, 17. Juli 2020 10:47
An: swift-project/pilotclient
Cc: tzobler; Mention
Betreff: Re: [swift-project/pilotclient] [CI] Generate Doxygen documentation in Github Actions (#43)

 

I guess the files aren't changing much between new commits/versions, right?
Then static webhosting via an AWS S3 bucket might be an option using AWS CLI with https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html. This will only upload changed files.

Pricing for the storage shouldn't be the problem but 0.005$ for 1.000 PUT requests. In my local build, we currently have ~21.000 files :(

Otherwise, we can ask @tzobler <https://github.com/tzobler>  if we might host it on FSC servers. (Around 1.4 GB disk usage).

**Comment by oktal3700** [comment]
@tzobler thank you very much. Redirecting should be no problem, once we figure out where to redirect to. That would be the final step.

I guess I would need the private key of a user with `ssh` write permissions to the directory where the docs would be located on the FSC webserver. This key would be stored as a GitHub Secret. You could send it to me via Discord. And I would also need the `ssh` URL and path where the files would be stored.

I was able to reduce the size to 238MB (of course this would increase if we write more classes). After uploading each new version of the docs, I would automatically delete the old version, but there would be a few seconds during which both the old and new docs would be stored on the server, so the size used would be double during those seconds.

The upload would be triggered by merging to the `master` branch.

**Comment by oktal3700** [comment]
I'm investigating the possibility of using Sphinx, Breathe, and Exhale to host the docs on [Read the Docs](https://readthedocs.com/). Hopefully this will be easier than running Doxygen on GitHub Actions, and release Thomas to keep working on other issues. I keep you posted.

**Comment by oktal3700** [comment]
Well Exhale threw a `MemoryError` after using 9GB on my home machine (I have 64GB total). The ReadTheDocs build container is limited to 3GB although we could ask to increase it. But it looks like Exhale is just a RAM hog for a large project like swift.

But I found [this](https://stackoverflow.com/questions/36064976/using-doxygen-in-read-the-docs) on StackOverflow showing how to deploy a vanilla Doxygen site on ReadTheDocs. It's a bit of a workaround because it's not really designed to be used that way, but it seems fine.

Doxygen documentation is online at https://apidocs.swift-project.org/
